<footer>
    <hr>
    <div class="container d-flex">
        <ul>
            <li><b>Title</b></li>
            <li>link</li>
            <li>link</li>
            <li>link</li>
        </ul>
        <ul>
            <li><b>Title</b></li>
            <li>link</li>
            <li>link</li>
            <li>link</li>
        </ul>
        <ul>
            <li><b>Title</b></li>
            <li>link</li>
            <li>link</li>
            <li>link</li>
        </ul>
        <div>image</div>
    </div>
</footer>